#!/bin/bash

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)"     # detached HEAD
branch_name=${branch_name##refs/heads/}

function submitTurn {
  echo 'Submitting game data...'
  git add gitwar.log &> /dev/null
  git commit -m "$1

$2" &> /dev/null

  git push origin "$branch_name" &> /dev/null
}

function silentSubmit {
  git add gitwar.log &> /dev/null
  git commit -m "$1" &> /dev/null
  git push origin "$branch_name" &> /dev/null
}

function silentPull {
  git pull origin "$branch_name" &> /dev/null
}

continue='Already up-to-date.'

function wait {
  echo -n 'Waiting for opponent to make their move...'
  while [ "$continue" = 'Already up-to-date.' ]; do
    continue=`git pull origin "$branch_name" 2> /dev/null`
  done

  # Call the app who called me and tell them the opponent took their turn

  echo
}

function reset {
  echo "Starting new game - make sure your opponent pulls the latest changes before they start playing"
  githead=`git log -1 --pretty=%H`
  echo "$githead" >> gitwar.games
  echo "" > gitwar.log
  git add gitwar.users gitwar.games gitwar.log &> /dev/null
  git commit -m 'Resetting game

RESET' &> /dev/null
  git push origin "$branch_name" &> /dev/null
}

logformat="%cd,%cn,%b"
function log {
  githead=`tail -1 gitwar.games`
  log=`git log --pretty="$logformat" "$githead".. | head -n -2 | tac | sed -e '$!N;s/^\n//' -e '$!N;s/\n$//'`
  echo "$log"
}

function firstLogLine {
  githead=`tail -1 gitwar.games`
  log=`git log --pretty="$logformat" "$githead".. | head -n -2 | tac | sed -e '$!N;s/^\n//'`
  echo "$log" | head -1
}

function lastLogLine {
  githead=`tail -1 gitwar.games`
  log=`git log --pretty="$logformat" "$githead".. | head -n -2 | tac | sed -e '$!N;s/\n$//'`
  echo "$log" | tail -1
}

if [ "$1" = "-w" ]; then
  wait
elif [ "$1" = "-c" ]; then
  reset
elif [ "$1" = "-s" ]; then
  silentSubmit "$2"
elif [ "$1" = "-p" ]; then
  silentPull
elif [ "$1" = "-l" ]; then
  if [ "$2" = "-head" ]; then
    firstLogLine
  elif [ "$2" = "-tail" ]; then
    lastLogLine
  else
    log
  fi
else
  submitTurn "$1" "$2"
  wait
fi
